export * from "./MainSection"
export * from "./BioSection"
export * from "./ProyectSection"
export * from "./ContactSection"
export * from "./Header"
export * from "./HeaderMobile"
export * from "./HeaderWeb"
export * from "./Dropdown"